<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.evently</groupId>
    <artifactId>evently-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>evt-grpc-contracts</module>
        <module>evt-commom-util</module>
        <module>evt-core-service</module>
        <module>evt-notification-service</module>
        <module>evt-open-service</module>
        <module>evt-bff</module>
    </modules>
</project>
